version: '3.8'

services:
  twitter-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
      - HEALTH_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - twitter-bot-network

networks:
  twitter-bot-network:
    driver: bridge

volumes:
  logs:
    driver: local